project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Open Science Tools"
  description: "As the expectations of researchers increase, publishing reproducible
      scientific articles becomes essential. However, choosing tools for these
      tasks can be difficult. This course aims to guide researchers through
      these challenges by introducing a workflow that utilizes Git, GitHub,
      and the Quarto scientific and technical publishing system for collaborative
      scientific writing."
  site-url: "https://ost-hs23.github.io/website/"

  repo-url: https://github.com/ost-hs23/website
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#eceef8"

  sidebar:
    background: "#eceef8"
    logo: "images/ghe-square-logo-vector.svg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ost-hs23/
        text: "GitHub organization"
    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: "Pre-course work"
        href: index.qmd
        contents:
          - href: 0-2-pre-work/01-github.qmd
            text: "Step 1: GitHub"
          - href: 0-2-pre-work/02-orcid.qmd
            text: "Step 2: ORCID"
          - href: 0-2-pre-work/03-zotero.qmd
            text: "Step 3: Zotero"
          - href: 0-2-pre-work/04-posit-cloud.qmd
            text: "Step 4: Posit Cloud"
          - href: 0-2-pre-work/05-element.qmd
            text: "Step 5: Element"
          - href: 0-2-pre-work/06-survey.qmd
            text: "Step 6: Survey"
          - href: 0-2-pre-work/07-reading.qmd
            text: "Step 7: Reading"
      - text: "---"
      - section: "Day 1"
        contents:
          - href: 1-1-hello-quarto/index.qmd
            text: "Hello Quarto"
          - href: 1-2-github/index.qmd
            text: "GitHub"
          - href: 1-3-documents/index.qmd
            text: "Documents"
          - href: 1-4-scholarly-writing/index.qmd
            text: "Scholarly writing"
      - text: "---"
      - href: syllabus.qmd
        text: "Syllabus"
      - text: "---"
      - section: "Other resources"
        contents:
          - href: 0-1-overview/index.qmd
            text: "ETH4D Lunch"
format:
  html:
    theme:
      light: [litera, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    include-in-header:
        - text: |
            <script defer data-domain="ost-hs23.github.io/website" src="https://plausible.io/js/script.js"></script>

freeze: auto
editor: source



